# Generated by Django 4.2.27 on 2026-02-05 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lesson_tasktype_task_lessonenrollement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonenrollement',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonenrollement',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='lessonenrollement',
            name='status',
            field=models.CharField(default='started', max_length=120),
        ),
    ]
