# Generated by Django 4.2.27 on 2026-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_lessonenrollement_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonenrollement',
            name='end_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
