# Generated by Django 4.2.27 on 2026-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_lessonenrollement_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonenrollement',
            name='earned_XP',
            field=models.FloatField(default=0),
        ),
    ]
