# Generated by Django 4.2.27 on 2026-02-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_lessonenrollement_earned_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonenrollement',
            name='earned_XP',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lessonenrollement',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
