# Generated by Django 4.2.27 on 2026-03-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_answer_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
